/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read API health and post count */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List posts using cursor pagination */
        get: operations["listPosts"];
        put?: never;
        /** Create a post */
        post: operations["createPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{postId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a post */
        get: operations["getPost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{postId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a post's comment tree */
        get: operations["listPostComments"];
        put?: never;
        /** Create a comment or reply */
        post: operations["createPostComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulate-load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add synthetic posts for the load simulation */
        post: operations["simulateLoad"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a cached, responsive derivative of an approved sample image
         * @description The server fetches only an image from the yavuzceliker/sample-images source repository, resizes it without enlargement, and returns the requested AVIF or WebP derivative. Responses are safe to retry and have immutable browser-cache semantics for one year.
         */
        get: operations["getImageDerivative"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        Post: {
            id: string;
            author: string;
            title: string;
            content: string;
            createdAt: number;
            commentCount: number;
        };
        CreatePostRequest: {
            author?: string;
            title: string;
            content?: string;
        };
        Comment: {
            id: string;
            postId: string;
            parentId: string | null;
            author: string;
            content: string;
            createdAt: number;
            depth: number;
            replies?: components["schemas"]["Comment"][];
        };
        CreateCommentRequest: {
            author?: string;
            content: string;
            parentId?: string | null;
        };
    };
    responses: {
        /** @description The request is invalid. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The requested resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        SearchQuery: string;
        Cursor: number;
        Limit: number;
        PostId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is available. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                        posts: number;
                    };
                };
            };
        };
    };
    listPosts: {
        parameters: {
            query?: {
                q?: components["parameters"]["SearchQuery"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of posts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        posts: components["schemas"]["Post"][];
                        nextCursor: number | null;
                        total: number;
                    };
                };
            };
        };
    };
    createPost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePostRequest"];
            };
        };
        responses: {
            /** @description The created post. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        post: components["schemas"]["Post"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
        };
    };
    getPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested post. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        post: components["schemas"]["Post"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listPostComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nested comments for a post. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        comments: components["schemas"]["Comment"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createPostComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentRequest"];
            };
        };
        responses: {
            /** @description The created comment. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        comment: components["schemas"]["Comment"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
        };
    };
    simulateLoad: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @default 500 */
                    count?: number;
                };
            };
        };
        responses: {
            /** @description Simulation result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        added: number;
                        tookMs: number;
                        totalPosts: number;
                    };
                };
            };
        };
    };
    getImageDerivative: {
        parameters: {
            query: {
                /** @example 640 */
                width: 320 | 640 | 1280;
                /**
                 * @description Cache-busting derivative version. The server accepts it so clients can version immutable URLs.
                 * @example 1
                 */
                v?: string;
                /** @example webp */
                format: "avif" | "webp";
            };
            header?: never;
            path: {
                /** @example image-1.jpg */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transformed image with one-year immutable browser caching. */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "image/avif": unknown;
                    "image/webp": unknown;
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description The upstream source image could not be fetched or transformed. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
